name = "gridstatus"
compatibility_date = "2026-05-19"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "gridstatus-db"
database_id = "c49b45c4-7b43-41c3-8e3c-7be261c66187"

[vars]
MONTHLY_PRICE_USD = "20"
REQUIRE_PAID_API = "true"
ALLOW_PUBLIC_REGISTER = "true"
STRIPE_PRODUCT_NAME = "GridStatus API"
